apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: userservice
  namespace: ase-8
  annotations:
     kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: sau-portal.de
      http:
        paths:
          - path: /masterdata
            pathType: Prefix
            backend:
              service:
                name: userservice
                port:
                  number: 8080
